### ISSUE TITLE
update wirecompat tests to v6

### ISSUE THREAD

**Issue by SimonCropp** [Particular/EndToEnd#1]
relates to: https://github.com/Particular/PlatformDevelopment/issues/378

**Comment by johnsimons** [comment]
I can look at this is no one else has claimed it yet

**Comment by SimonCropp** [comment]
@johnsimons fine with me. i am unsure if we should continue down the console approach. or do a proper management of appdomains for each scenario. feel free to go either way

**Comment by petersgiles** [comment]
I'm in too, I think I'll learn a lot helping out with this one

**Comment by johnsimons** [comment]
This is pretty much complete, the following issues were found:
- https://github.com/Particular/NServiceBus/pull/3576
- https://github.com/Particular/NServiceBus.Callbacks/pull/19

Once those are merged, I will do the last update and merge all the changes

**Comment by andreasohlund** [comment]
Both pulls are merged, can this be closed? cc @weralabaj

**Comment by weralabaj** [comment]
@andreasohlund there's outstanding issue of using mocks in tests for callbacks, when they are ready, but it's tracked in the issue Tim is working on.
So let's close this one.
