### ISSUE TITLE
Two locations with documents

### ISSUE THREAD

**Issue by dvdstelt** [Particular/EndToEnd#171]
There are documents in /src/ and in /docs/ where /src/ sometimes is more recent than /docs/ documentation

Example of `readme` and `getting started`

Original : https://github.com/Particular/EndToEnd/blob/master/docs/performance-gettingstarted.md
Updated : https://github.com/Particular/EndToEnd/blob/master/src/PerformanceTests/readme.md

This should be fixed and under /docs/ where it is more easily found.

**Comment by ramonsmits** [comment]
I like that all stuff related to perftests in located under `/src/PerformanceTests`

I rather delete `/docs/performance-gettingstarted.md` and update `/README.md`.

**Comment by dvdstelt** [comment]
I like /docs/ because then its obvious to everyone that there's doco. Not so much when it's under /src/. If so, then rename it to /docsrc/ but that violates SRP. Why would we want to put doco there? I don't understand the reasoning.
