### ISSUE TITLE
De commission Splunk

### ISSUE THREAD

**Issue by dvdstelt** [Particular/EndToEnd#255]
Remove Splunk appender, so @gbiellem can upgrade Octopus and we can come up with an alternative.

**Comment by ramonsmits** [comment]
@dvdstelt @gbiellem See #255 is that sufficient? We would still be able to run the performance tests on the build server but not using Splunk as the log destination.

**Comment by dvdstelt** [comment]
I would say so. I just merged it. You didn't put [WIP] in front of it! ;-)
