### ISSUE TITLE
WireCompatTest broken on build server

### ISSUE THREAD

**Issue by SimonCropp** [Particular/EndToEnd#29]
https://builds.particular.net/viewLog.html?buildId=157732&buildTypeId=ProductionStagingTests_WireCompatability&tab=buildLog

works fine locally. I suspect this will be a non trivial rabbit hole. so am raising as an issue

**Comment by johnsimons** [comment]
I'll look into it

**Comment by johnsimons** [comment]
it seems to be good now

**Comment by SimonCropp** [comment]
@johnsimons thanks
