### ISSUE TITLE
Clarify what's the purpose of EndToEnd tests

### ISSUE THREAD

**Issue by weralabaj** [Particular/EndToEnd#4]
A few questions came up during today's transport sync:
- How is this repo related to ProductionTests?
- What tests should be moved/created here?
- What is the purpose of this repo, what benefits should it provide for people accessing it?
- What assumptions we make for tests here (manual/automated, infrastructure, etc.)?

Those things should be captured in Readme file.

**Comment by SeanFeldman** [comment]
[Readme.md](https://github.com/Particular/EndToEnd/blob/master/README.md) should address this.
[My question](https://github.com/Particular/EndToEnd/issues/2#issuecomment-197403936) to @andreasohlund would be unnecessary if I could find that information.

**Comment by SimonCropp** [comment]
> How is this repo related to ProductionTests

This is the replacement for ProductionTests. there is too much history in ProductionTests to look through for password/comments/connections string.

So this is a clean break with no history

> What tests should be moved/created here

All of them that are still relevant and you want to be publicly accessible

> What is the purpose of this repo, what benefits should it provide for people accessing it?

We want to be able to point to our full multi-version tests to show the quality we are striving for. we want it open source for all the reasons we want anything else open source

> What assumptions we make for tests here (manual/automated, infrastructure, etc.)?

As much as possible automated + running on TC periodically. but manual is acceptance for edge cases

> Those things should be captured in Readme file.

yes. want to do a PR ;)

**Comment by SeanFeldman** [comment]
@SimonCropp Thank you.

> yes. want to do a PR ;)

Based on how you answered, we should thank you for doing the PR.

**Comment by andreasohlund** [comment]
>Based on how you answered, we should thank you for doing the PR.

I propose you or @weralabaj creates a pull based on @SimonCropp 's answers to make sure they make sense and then ask Simon to review merge the pull?
