### ISSUE TITLE
Investigate if IProfile is still needed

### ISSUE THREAD

**Issue by dvdstelt** [Particular/EndToEnd#56]
I think IProfile is no longer needed and IProfile.Configure should never be called. This is all taken care off by BaseRunner.
I'm currently in a somewhat larger PR and I don't want it included in it, therefor I created an issue anyone can pick up.
Ping me if you need more info on BaseRunner.

**Comment by ramonsmits** [comment]
@dvdstelt IProfile is used by all persistence, transports and distributions to configure the relevant instance configuration.
