### ISSUE TITLE
Mimic real world scenarios in tests instead of empty handlers

### ISSUE THREAD

**Issue by dvdstelt** [Particular/EndToEnd#83]
It was communicated that this was raised at the V6 PlatformDev sync this morning.

Currently our handlers aren't doing anything at all. We should add some asynchronous io operation to our empty handlers so that our tests mimic the real world scenarios more and we can provide more accurate performance data.

**Comment by dvdstelt** [comment]
The reason we have empty handlers is because we want raw NServiceBus performance numbers, not being influenced by anything outside of the scope of NServiceBus. 

Besides that, there are so many real world scenarios possible, that it's not doable to pick a single scenario and say that our performance tests are anything like 'the real world'. Probably the only reason to do this is make NServiceBus v6 look better, because it's fully async and could/should benefit from doing some async operation in the handlers. I don't think it's a fair comparison then anymore.

**Comment by ramonsmits** [comment]
@dvdstelt This is here to clarify our decision on empty messages correct? If so, can it be closed? Maybe we have to put this in a document instead and then close it?

**Comment by dvdstelt** [comment]
Correct. Yes. Good idea.
