### ISSUE TITLE
TaskHelper runs sequentially for V5 due to Task.FromResult(0) in V5 Session implementation

### ISSUE THREAD

**Issue by ramonsmits** [Particular/EndToEnd#98]
TaskHelper runs sequentially for V5 due to Task.FromResult(0) in V5 Session implementation although its expected that all tasks are processed concurrently.

## Code

* https://github.com/Particular/EndToEnd/blob/perf-tests/src/PerformanceTests/Common/Scenarios/LoopRunner.cs#L60

```c#
 await TaskHelper.ParallelFor(BatchSize, () => SendMessage(session));
```

* https://github.com/Particular/EndToEnd/blob/perf-tests/src/PerformanceTests/Utils/TaskHelper.cs#L6

```c#
var sends = new Task[count];
for (var i = 0; i < count; i++) sends[i] = action();
await Task.WhenAll(sends);
```

* https://github.com/Particular/EndToEnd/blob/perf-tests/src/PerformanceTests/NServiceBus5/Session.cs#L36

```c#
if (localAddress == null)
    instance.SendLocal(message);
else
    instance.Send(localAddress, message);

return Task.FromResult(0);
```

## Possible solutions:

- Convert to a Parallel.For
- Use Task.Yield to break sequential processing

Thanks @SzymonPobiega for this catch!

**Comment by danielmarbach** [comment]
I'm back on Monday. Free to help if needed.
